-- Lyrics PDF Library: complete setup for a new Supabase project.
-- Run in Supabase Dashboard -> SQL Editor, then run admin_setup.sql.

begin;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
revoke all on table public.admin_users from anon, authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

create table if not exists public.songs (
  id uuid primary key default gen_random_uuid(),
  title text not null check (length(btrim(title)) between 1 and 160),
  artist text not null check (length(btrim(artist)) between 1 and 160),
  album text,
  release_year integer check (release_year between 1800 and 2100),
  language text,
  genre text,
  notes text,
  youtube_video_id text not null check (youtube_video_id ~ '^[A-Za-z0-9_-]{11}$'),
  pdf_path text not null unique,
  original_filename text not null,
  uploader_id uuid not null default auth.uid() references auth.users(id) on delete restrict,
  uploader_display_name text check (length(btrim(uploader_display_name)) between 1 and 120),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.songs
  add column if not exists uploader_display_name text
  check (length(btrim(uploader_display_name)) between 1 and 120);

create table if not exists public.lyric_cues (
  id bigint generated by default as identity primary key,
  song_id uuid not null references public.songs(id) on delete cascade,
  line_index integer not null check (line_index >= 0),
  start_ms integer not null check (start_ms >= 0),
  end_ms integer check (end_ms is null or end_ms > start_ms),
  text text not null check (length(btrim(text)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (song_id, line_index)
);

create table if not exists public.tags (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (length(btrim(name)) between 1 and 80),
  slug text not null unique check (
    length(slug) between 1 and 80
    and slug = lower(slug)
    and slug !~ '\\s'
  ),
  created_at timestamptz not null default now()
);

create unique index if not exists tags_name_lower_unique_idx on public.tags (lower(name));

create table if not exists public.song_tags (
  song_id uuid not null references public.songs(id) on delete cascade,
  tag_id uuid not null references public.tags(id) on delete restrict,
  primary key (song_id, tag_id)
);

create index if not exists songs_status_created_idx on public.songs (status, created_at desc);
create index if not exists songs_uploader_status_idx on public.songs (uploader_id, status);
create index if not exists songs_title_lower_idx on public.songs (lower(title));
create index if not exists songs_artist_lower_idx on public.songs (lower(artist));
create index if not exists songs_language_idx on public.songs (language) where language is not null;
create index if not exists songs_genre_idx on public.songs (genre) where genre is not null;
create index if not exists songs_release_year_idx on public.songs (release_year desc) where release_year is not null;
create index if not exists lyric_cues_song_line_idx on public.lyric_cues (song_id, line_index);
create index if not exists lyric_cues_song_start_idx on public.lyric_cues (song_id, start_ms);
create index if not exists song_tags_tag_idx on public.song_tags (tag_id, song_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.set_song_uploader_display_name()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  user_metadata jsonb;
  app_metadata jsonb;
  resolved_name text;
begin
  select raw_user_meta_data, raw_app_meta_data
  into user_metadata, app_metadata
  from auth.users
  where id = new.uploader_id;

  if app_metadata ->> 'provider' = 'google'
     or app_metadata -> 'providers' @> '["google"]'::jsonb then
    resolved_name := coalesce(
      nullif(btrim(user_metadata ->> 'full_name'), ''),
      nullif(btrim(user_metadata ->> 'name'), ''),
      nullif(btrim(user_metadata ->> 'display_name'), '')
    );
  end if;

  resolved_name := coalesce(
    resolved_name,
    nullif(btrim(user_metadata ->> 'display_name'), ''),
    nullif(btrim(user_metadata ->> 'full_name'), ''),
    nullif(btrim(user_metadata ->> 'name'), ''),
    nullif(btrim(user_metadata ->> 'preferred_username'), ''),
    nullif(btrim(user_metadata ->> 'user_name'), ''),
    nullif(btrim(user_metadata ->> 'username'), ''),
    new.uploader_id::text
  );

  new.uploader_display_name := left(
    regexp_replace(resolved_name, '[[:cntrl:]]', '', 'g'),
    120
  );
  return new;
end;
$$;

revoke all on function public.set_song_uploader_display_name() from public;

drop trigger if exists songs_set_updated_at on public.songs;
drop trigger if exists songs_set_uploader_display_name on public.songs;
create trigger songs_set_uploader_display_name
before insert or update on public.songs
for each row execute function public.set_song_uploader_display_name();

update public.songs
set uploader_display_name = uploader_id::text
where uploader_display_name is null;

drop trigger if exists songs_set_updated_at on public.songs;
create trigger songs_set_updated_at
before update on public.songs
for each row execute function public.set_updated_at();

drop trigger if exists lyric_cues_set_updated_at on public.lyric_cues;
create trigger lyric_cues_set_updated_at
before update on public.lyric_cues
for each row execute function public.set_updated_at();

alter table public.songs enable row level security;
alter table public.lyric_cues enable row level security;
alter table public.tags enable row level security;
alter table public.song_tags enable row level security;

grant select on public.songs, public.lyric_cues, public.tags, public.song_tags to anon, authenticated;
grant insert, update, delete on public.songs to authenticated;
grant insert, delete on public.song_tags to authenticated;
grant insert, update, delete on public.lyric_cues, public.tags to authenticated;
grant usage, select on sequence public.lyric_cues_id_seq to authenticated;

drop policy if exists "Visible songs are readable" on public.songs;
create policy "Visible songs are readable"
on public.songs for select
to anon, authenticated
using (
  status = 'approved'
  or uploader_id = (select auth.uid())
  or (select public.is_admin())
);

drop policy if exists "Users submit pending songs" on public.songs;
create policy "Users submit pending songs"
on public.songs for insert
to authenticated
with check (
  uploader_id = (select auth.uid())
  and status = 'pending'
  and split_part(pdf_path, '/', 1) = (select auth.uid()::text)
);

drop policy if exists "Owners edit pending songs" on public.songs;
create policy "Owners edit pending songs"
on public.songs for update
to authenticated
using (
  (uploader_id = (select auth.uid()) and status = 'pending')
  or (select public.is_admin())
)
with check (
  (uploader_id = (select auth.uid()) and status = 'pending')
  or (select public.is_admin())
);

drop policy if exists "Owners delete pending songs" on public.songs;
create policy "Owners delete pending songs"
on public.songs for delete
to authenticated
using (
  (uploader_id = (select auth.uid()) and status = 'pending')
  or (select public.is_admin())
);

drop policy if exists "Visible song cues are readable" on public.lyric_cues;
create policy "Visible song cues are readable"
on public.lyric_cues for select
to anon, authenticated
using (
  exists (
    select 1 from public.songs s
    where s.id = song_id
      and (
        s.status = 'approved'
        or s.uploader_id = (select auth.uid())
        or (select public.is_admin())
      )
  )
);

drop policy if exists "Admins manage lyric cues" on public.lyric_cues;
create policy "Admins manage lyric cues"
on public.lyric_cues for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Visible song tags are readable" on public.song_tags;
create policy "Visible song tags are readable"
on public.song_tags for select
to anon, authenticated
using (
  exists (
    select 1 from public.songs s
    where s.id = song_id
      and (
        s.status = 'approved'
        or s.uploader_id = (select auth.uid())
        or (select public.is_admin())
      )
  )
);

drop policy if exists "Owners manage pending song tags" on public.song_tags;
create policy "Owners manage pending song tags"
on public.song_tags for insert
to authenticated
with check (
  exists (
    select 1 from public.songs s
    where s.id = song_id
      and (
        (s.uploader_id = (select auth.uid()) and s.status = 'pending')
        or (select public.is_admin())
      )
  )
);

drop policy if exists "Owners remove pending song tags" on public.song_tags;
create policy "Owners remove pending song tags"
on public.song_tags for delete
to authenticated
using (
  exists (
    select 1 from public.songs s
    where s.id = song_id
      and (
        (s.uploader_id = (select auth.uid()) and s.status = 'pending')
        or (select public.is_admin())
      )
  )
);

drop policy if exists "Visible tags are readable" on public.tags;
create policy "Visible tags are readable"
on public.tags for select
to anon, authenticated
using (
  (select public.is_admin())
  or exists (
    select 1
    from public.song_tags st
    join public.songs s on s.id = st.song_id
    where st.tag_id = id
      and (s.status = 'approved' or s.uploader_id = (select auth.uid()))
  )
);

drop policy if exists "Signed in users read available tags" on public.tags;
create policy "Signed in users read available tags"
on public.tags for select
to authenticated
using (true);

drop policy if exists "Admins create tags" on public.tags;
create policy "Admins create tags"
on public.tags for insert to authenticated
with check ((select public.is_admin()));

drop policy if exists "Admins update tags" on public.tags;
create policy "Admins update tags"
on public.tags for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Admins delete tags" on public.tags;
create policy "Admins delete tags"
on public.tags for delete to authenticated
using ((select public.is_admin()));

create or replace function public.set_song_tags(p_song_id uuid, p_tag_ids uuid[])
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.songs s
    where s.id = p_song_id
      and (
        (s.uploader_id = (select auth.uid()) and s.status = 'pending')
        or public.is_admin()
      )
  ) then
    raise exception 'Not allowed to update tags for this song';
  end if;

  if exists (
    select 1 from unnest(coalesce(p_tag_ids, array[]::uuid[])) requested(id)
    left join public.tags t on t.id = requested.id
    where t.id is null
  ) then
    raise exception 'Unknown tag id';
  end if;

  delete from public.song_tags where song_id = p_song_id;
  insert into public.song_tags (song_id, tag_id)
  select p_song_id, id
  from unnest(coalesce(p_tag_ids, array[]::uuid[])) requested(id)
  on conflict do nothing;
end;
$$;

revoke all on function public.set_song_tags(uuid, uuid[]) from public;
grant execute on function public.set_song_tags(uuid, uuid[]) to authenticated;

create or replace function public.replace_song_lyric_cues(p_song_id uuid, p_cues jsonb)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  inserted_count integer;
begin
  if not public.is_admin() then
    raise exception 'Administrator access required';
  end if;
  if not exists (select 1 from public.songs where id = p_song_id) then
    raise exception 'Song not found';
  end if;
  if jsonb_typeof(coalesce(p_cues, '[]'::jsonb)) <> 'array' then
    raise exception 'Cues must be a JSON array';
  end if;

  delete from public.lyric_cues where song_id = p_song_id;
  insert into public.lyric_cues (song_id, line_index, start_ms, end_ms, text)
  select p_song_id, cue.line_index, cue.start_ms, cue.end_ms, btrim(cue.text)
  from pg_catalog.jsonb_to_recordset(coalesce(p_cues, '[]'::jsonb))
    as cue(line_index integer, start_ms integer, end_ms integer, text text)
  order by cue.line_index;

  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;

revoke all on function public.replace_song_lyric_cues(uuid, jsonb) from public;
grant execute on function public.replace_song_lyric_cues(uuid, jsonb) to authenticated;

create or replace function public.delete_tag(p_tag_id uuid, p_confirm_used boolean default false)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  usage_count integer;
begin
  if not public.is_admin() then
    raise exception 'Administrator access required';
  end if;
  select count(*) into usage_count from public.song_tags where tag_id = p_tag_id;
  if usage_count > 0 and not p_confirm_used then
    raise exception 'Tag is used by % songs', usage_count;
  end if;
  delete from public.song_tags where tag_id = p_tag_id;
  delete from public.tags where id = p_tag_id;
  return usage_count;
end;
$$;

revoke all on function public.delete_tag(uuid, boolean) from public;
grant execute on function public.delete_tag(uuid, boolean) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('lyrics-pdfs', 'lyrics-pdfs', false, 52428800, array['application/pdf'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Users upload lyrics PDFs to own folder" on storage.objects;
create policy "Users upload lyrics PDFs to own folder"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'lyrics-pdfs'
  and lower(storage.extension(name)) = 'pdf'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Authorized readers access lyrics PDFs" on storage.objects;
create policy "Authorized readers access lyrics PDFs"
on storage.objects for select to anon, authenticated
using (
  bucket_id = 'lyrics-pdfs'
  and exists (
    select 1 from public.songs s
    where s.pdf_path = name
      and (
        s.status = 'approved'
        or s.uploader_id = (select auth.uid())
        or (select public.is_admin())
      )
  )
);

drop policy if exists "Owners remove pending or orphan lyrics PDFs" on storage.objects;
create policy "Owners remove pending or orphan lyrics PDFs"
on storage.objects for delete to authenticated
using (
  bucket_id = 'lyrics-pdfs'
  and (
    (select public.is_admin())
    or (
      (storage.foldername(name))[1] = (select auth.uid()::text)
      and (
        not exists (select 1 from public.songs s where s.pdf_path = name)
        or exists (
          select 1 from public.songs s
          where s.pdf_path = name
            and s.uploader_id = (select auth.uid())
            and s.status = 'pending'
        )
      )
    )
  )
);

commit;
